../registers/acc.v
../registers/alu.v
../registers/mar.v
../registers/mbr.v
../registers/pc.v
../registers/ir.v
../registers/reg_top.v
../memory/clk_divider.v
../memory/external_bus.v
../memory/top_data_ram.v
../memory/top_instr_rom.v
../memory/uart.v
../memory/fifo.v
../memory/bram_instr.v
../control_unit/cu_control_address_register.v
../control_unit/cu_control_buffer_register.v
../control_unit/cu_control_memory.v
../control_unit/cu_control_top.v
../top/cpu_top.v