# For top.v
../registers/acc.v
../registers/alu.v
../registers/mar.v
../registers/mbr.v
../registers/pc.v
../registers/ir.v
../registers/reg_top.v
../memory/clk_divider.v
../memory/external_bus.v
../memory/top_data_ram.v
../memory/top_instr_rom.v
../memory/uart.v
../memory/fifo.v
../memory/bram_instr.v
../control_unit/cu_control_address_register.v
../control_unit/cu_control_buffer_register.v
../control_unit/cu_control_memory.v
../control_unit/cu_top.v
../top/cpu_top.v
../top/top.v
../user_interface/key_jitter.v
../user_interface/seven_segment.v
../user_interface/top_seven_segment.v
../user_interface/led_display.v
../sim/tb_top.v
